<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content */
?>
<?php
$imagekitMLWidgetOptions = $block->getImageKitMediaLibraryWidgetOptions();
?>

<div class="media-gallery-modal" data-mage-init='{"mediabrowser": <?= $block->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
  <div class="page-main-actions">
    <div class="page-actions">
      <div class="page-actions-inner">
        <div class="page-action-buttons">
          <?= $block->getButtonsHtml() ?>
        </div>
      </div>
    </div>
  </div>
  <div class="side-col"><?= $block->getChildHtml('wysiwyg_images.tree') ?></div>
  <div class="main-col">
    <div id="error-message" data-action="show-error"></div>

    <?php if ($imagekitMLWidgetOptions) : ?>
      <button id="media_gallery_add_from_imagekit_button" title="<?= $block->escapeHtml(__('Add from ImageKit')) ?>" data-role="add-from-imagekit-button" type="button" data-mage-init='{"imagekitMediaLibraryModal": <?= $imagekitMLWidgetOptions ?>}' class="action-secondary add-from-imagekit-button imagekit-button-with-logo lg-margin-bottom">
        <span><?= $block->escapeHtml(__('Add from ImageKit')) ?></span>
      </button>
    <?php endif; ?>
    <div id="contents-uploader" class="contents-uploader"><?= $block->getChildHtml('wysiwyg_images.uploader') ?></div>
    <div id="contents"></div>
  </div>
</div>